inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - Gemfile
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 130
Style/LambdaCall:
  Enabled: false
